config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  mount Sidekiq::Web => '/admin/sidekiq'

  resources :profiles, path: '/' do
    get 'scan', action: :scan, on: :member
  end

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end


  scope '/v1', format: true, constraints: { format: 'json' } do
    resources :profiles
  end


  root to: 'profiles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blob.rb
class Blob < ApplicationRecord
  belongs_to :scan, optional: true
  has_many   :diffs, class_name: 'Blob', foreign_key: 'base_id'
  belongs_to :base, class_name: 'Blob', optional: true

  enum diff_format: [ :diff, :vcdiff ]
  enum status: [ :fadded , :fremoved, :fchanged, :funchanged ]

  scope :sorted_link, -> { order(linked_index: :asc) }

  def full_content_path
  end
end

# == Schema Information
#
# Table name: blobs
#
#  id           :integer          not null, primary key
#  path         :string
#  content_hash :binary           not null
#  base_id      :integer
#  link_index   :integer
#  scan_id      :integer
#  diff_format  :integer
#  content_path :string
#  byte_size    :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  status       :integer          default("0")
#  modified_at  :datetime
#
# Indexes
#
#  index_blobs_on_base_id                          (base_id)
#  index_blobs_on_content_hash                     (content_hash)
#  index_blobs_on_path_and_base_id_and_link_index  (path,base_id,link_index) UNIQUE
#  index_blobs_on_scan_id                          (scan_id)
#

app/models/profile.rb
require 'dropsquare/scanner'

class Profile < ApplicationRecord
  has_many :scans

  belongs_to :user
  belongs_to :latest_scan, class_name: 'Scan', optional: true

  validates :name, :directory_path, presence: true

  scope :with_latest_scan, -> {
    left_outer_joins(:latest_scan)
      .select(<<-EOQ)
        scans.start_time as scan_start_time,
        scans.end_time as scan_end_time,
        scans.byte_size as byte_size,
        scans.files_count as files_count,
        profiles.*
      EOQ
  }

  def scan
    scanner = DropSquare::Scanner.new(latest_scan, Settings.scan.basedir)
    result = scanner.scan(directory_path)
    transaction do
      cscan = scans.create!(result[:scan_params])
      result[:blobs].each do |blob|
        blob.scan_id = cscan.id
        blob.save!
      end
      self.latest_scan = cscan
      save!
    end
  end
end

# == Schema Information
#
# Table name: profiles
#
#  id              :integer          not null, primary key
#  name            :string
#  directory_path  :string
#  last_scanned_at :datetime
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#  latest_scan_id  :integer
#
# Indexes
#
#  index_profiles_on_latest_scan_id    (latest_scan_id)
#  index_profiles_on_user_id           (user_id)
#  index_profiles_on_user_id_and_name  (user_id,name) UNIQUE
#

app/models/scan.rb
class Scan < ApplicationRecord
  belongs_to :profile
  has_many :blobs

  before_create :put_hash

  private

  def put_hash
    self.scan_hash = SecureRandom.random_bytes 16
  end
end

# == Schema Information
#
# Table name: scans
#
#  id             :integer          not null, primary key
#  start_time     :datetime
#  end_time       :datetime
#  scan_hash      :binary           not null
#  profile_id     :integer
#  directory_tree :binary
#  byte_size      :integer
#  files_count    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_scans_on_profile_id  (profile_id)
#  index_scans_on_scan_hash   (scan_hash) UNIQUE
#

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic secure: true, size: 164, filetype: :jpg

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :profiles, dependent: :destroy

  def total_files_count
    Rails.cache.fetch("#{id}/files_count") do
      profiles.joins(:latest_scan)
        .select('user_id, sum(scans.files_count) files_count')
        .group('user_id')
        .first&.files_count
    end.to_i
  end

  def total_storage_used
    Rails.cache.fetch("#{id}/storage") do
      profiles.joins(:latest_scan)
        .select('user_id, sum(byte_size) storage')
        .group('user_id')
        .first&.storage
    end.to_i
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def current_page
    page = params[:page].to_i
    page <= 0 ? 1 : page
  end

  def assign_user
    @user = current_user
    @profiles = current_user.profiles.with_latest_scan.page(current_page)
    @profile_count = current_user.profiles.count
  end
end

app/controllers/custom_devise_controller.rb
class CustomDeviseController < ApplicationController
  layout 'prelogin'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :assign_user

  def index
    @newprofile = current_user.profiles.build
  end

  def create
    current_user.profiles.create!(profile_params)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :created }
    end
  end

  def show
    @profile = @profiles.find(params[:id])
    @files = @profile.latest_scan.blobs
  end

  def scan
    @profile = @profiles.find(params[:id])
    jid = ScanWorker.perform_async(current_user.id, @profile.name)
    render json: { watch: "/scan-#{jid}" }
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :directory_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/application/_user_info.html.erb
<div class="columns">
  <div class="column is-one-third">
    <div class="columns">
      <div class="column">
        <aside class="menu">
          <p class="menu-label">
          User Menu
          </p>
          <ul class="menu-list">
            <li><%= link_to 'Browse Profile', root_path %></li>
            <li><%= link_to 'Edit User Info', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path %></li>
          </ul>
        </aside>
      </div>
    </div>
  </div>
  <div class="column is-two-third">
    <div class="media">
      <div class="media-left">
        <figure class="box image is-128x128">
          <img src="<%= @user.gravatar_url %>"></img>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <div class="title"><%=@user.email%></div>
          <div class="subtitle">Owns <%= @profile_count %> profile(s)</div>
          <div class="columns">
            <div class="column">
              <span class="title"><%= number_with_delimiter @user.total_files_count %></span>
              <span class="subtitle">Files</span>
            </div>
            <div class="column">
              <div class="title"><%= number_to_human_size @user.total_storage_used %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DropSquare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div class="columns is-centered">
      <div class="column main-container">
        <%= render 'user_info' %>
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
    <script type="text/javascript">
      <%= yield :embedded_javascript %>
    </script>
  </body>
</html>

app/views/layouts/prelogin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DropSquare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_new_profile_form.html.erb
<div class="columns">
  <div class="column">
    <div id="add-newprofile" class="button is-primary is-pulled-right">
      <span class="icon">
        <i class="fa fa-plus"></i>
      </span>
      <span>New Profile</span>
    </div>
  </div>
</div>

<div id="newprofile-modal" class="modal">
  <div class="modal-background"></div>
  <div class="box modal-content">
    <%= form_for(@newprofile, html: { class: 'columns' }) do |f| %>
      <%= f.text_field :name, autofocus: true, class: 'column textinput-h', placeholder: 'Profile Name' %>
      <%= f.text_field :directory_path, class: 'column textinput-h', placeholder: 'Directory Path' %>
      <div class="actions">
        <%= f.submit "Create", class: 'button is-primary button-h' %>
      </div>
    <% end %>
  </div>
  <button class="modal-close"></button>
</div>

app/views/profiles/index.html.erb
<%= render 'new_profile_form' %>
<div class="columns">
  <table class="table">
    <thead>
      <th>Profile Name</th>
      <th>Files</th>
      <th>Storage</th>
      <th>Last Scan</th>
    </thead>
    <tbody>
      <% @profiles.each do | profile| %>
        <tr>
          <td><%= link_to profile.name, profile_path(profile) %></td>
          <td><%= number_with_delimiter profile.files_count.to_i %></td>
          <td><%= number_to_human_size profile.byte_size.to_i %></td>
          <td><%= profile.scan_end_time %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/profiles/show.html.erb
<% content_for :embedded_javascript do %>
  window.current_profile_id = <%= @profile.id %>;
<% end %>

<div id="scan-result" class="columns">
  <div class="column">
    <span class="title"><%= @profile.name %></span>
    <span class="subtitle">scan result:</span>

    <span id="result-text" class="content">
      <strong>0</strong> added, <strong>0</strong> changed, <strong>0</strong> removed.
    </span>
  </div>
  <div class="column is-2">
    <div id="btn-scan" class="button is-primary is-pulled-right">
      <span class="icon">
        <i class="fa fa-refresh"></i>
      </span>
      <span>Scan</span>
    </div>
  </div>
</div>
<div class="columns is-centered has-text-centered">
</div>
<nav class="level">
  <div class="level-left">
    <div class="level-item">
      <p class="subtitle">Filter:</p>
    </div>
    <div class="level-item field has-addons">
      <p class="control">
      <a id="btn-filter-new" class="button is-light">
        <span class="icon is-small">
          <i class="fa fa-plus"></i>
        </span>
        <span>new</span>
      </a>
      </p>
      <p class="control">
      <a id="btn-filter-removed" class="button is-light is-active">
        <span class="icon is-small">
          <i class="fa fa-minus"></i>
        </span>
        <span>removed</span>
      </a>
      </p>
      <p class="control">
      <a id="btn-filter-changed" class="button is-light">
        <span class="icon is-small">
          <i class="fa fa-edit"></i>
        </span>
        <span>changed</span>
      </a>
      </p>
      <p class="control">
      <a id="btn-filter-unchanged" class="button is-light">
        <span class="icon is-small">
          <i class="fa fa-square-o"></i>
        </span>
        <span>unchanged</span>
      </a>
      </p>
    </div>
  </div>
  <div class="level-right">
		<p class="control is-expanded">
		<span class="select is-fullwidth">
			<select>
        <% @profile.scans.order('id desc').each_with_index do |sc| %>
          <option><%= "#{sc.scan_hash.unpack('H*')[0][0..8]} (#{sc.end_time})" %></option>
        <% end %>
			</select>
		</span>
		</p>
	</div>
</nav>
<div class="columns">
	<table class="table">
		<thead>
			<th><i class="fa fa-square-o"></i></th>
			<th>File Name</th>
			<th>Size</th>
			<th>Last Modified</th>
		</thead>
		<tbody>
      <% @files.each do |f| %>
        <tr>
          <td></td><td><%= f.path %></td><td><%= number_to_human_size f.byte_size %></td><td><%= f.modified_at %></td>
        </tr>
      <% end %>
		</tbody>
	</table>
</div>